package com.javashop.pojo;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proid
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    private Integer proid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proname
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    private String proname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proprice
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    private String proprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proaddress
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    private String proaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.proimage
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    private String proimage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proid
     *
     * @return the value of product.proid
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public Integer getProid() {
        return proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proid
     *
     * @param proid the value for product.proid
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public void setProid(Integer proid) {
        this.proid = proid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proname
     *
     * @return the value of product.proname
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public String getProname() {
        return proname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proname
     *
     * @param proname the value for product.proname
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public void setProname(String proname) {
        this.proname = proname == null ? null : proname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proprice
     *
     * @return the value of product.proprice
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public String getProprice() {
        return proprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proprice
     *
     * @param proprice the value for product.proprice
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public void setProprice(String proprice) {
        this.proprice = proprice == null ? null : proprice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proaddress
     *
     * @return the value of product.proaddress
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public String getProaddress() {
        return proaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proaddress
     *
     * @param proaddress the value for product.proaddress
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public void setProaddress(String proaddress) {
        this.proaddress = proaddress == null ? null : proaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.proimage
     *
     * @return the value of product.proimage
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public String getProimage() {
        return proimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.proimage
     *
     * @param proimage the value for product.proimage
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public void setProimage(String proimage) {
        this.proimage = proimage == null ? null : proimage.trim();
    }

    @Override
    public String toString() {
        return "Product{" +
                "proid=" + proid +
                ", proname='" + proname + '\'' +
                ", proprice='" + proprice + '\'' +
                ", proaddress='" + proaddress + '\'' +
                ", proimage='" + proimage + '\'' +
                '}';
    }
}