package com.javashop.pojo;

import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProidIsNull() {
            addCriterion("proid is null");
            return (Criteria) this;
        }

        public Criteria andProidIsNotNull() {
            addCriterion("proid is not null");
            return (Criteria) this;
        }

        public Criteria andProidEqualTo(Integer value) {
            addCriterion("proid =", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidNotEqualTo(Integer value) {
            addCriterion("proid <>", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidGreaterThan(Integer value) {
            addCriterion("proid >", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidGreaterThanOrEqualTo(Integer value) {
            addCriterion("proid >=", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidLessThan(Integer value) {
            addCriterion("proid <", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidLessThanOrEqualTo(Integer value) {
            addCriterion("proid <=", value, "proid");
            return (Criteria) this;
        }

        public Criteria andProidIn(List<Integer> values) {
            addCriterion("proid in", values, "proid");
            return (Criteria) this;
        }

        public Criteria andProidNotIn(List<Integer> values) {
            addCriterion("proid not in", values, "proid");
            return (Criteria) this;
        }

        public Criteria andProidBetween(Integer value1, Integer value2) {
            addCriterion("proid between", value1, value2, "proid");
            return (Criteria) this;
        }

        public Criteria andProidNotBetween(Integer value1, Integer value2) {
            addCriterion("proid not between", value1, value2, "proid");
            return (Criteria) this;
        }

        public Criteria andPronameIsNull() {
            addCriterion("proname is null");
            return (Criteria) this;
        }

        public Criteria andPronameIsNotNull() {
            addCriterion("proname is not null");
            return (Criteria) this;
        }

        public Criteria andPronameEqualTo(String value) {
            addCriterion("proname =", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotEqualTo(String value) {
            addCriterion("proname <>", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameGreaterThan(String value) {
            addCriterion("proname >", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameGreaterThanOrEqualTo(String value) {
            addCriterion("proname >=", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLessThan(String value) {
            addCriterion("proname <", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLessThanOrEqualTo(String value) {
            addCriterion("proname <=", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameLike(String value) {
            addCriterion("proname like", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotLike(String value) {
            addCriterion("proname not like", value, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameIn(List<String> values) {
            addCriterion("proname in", values, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotIn(List<String> values) {
            addCriterion("proname not in", values, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameBetween(String value1, String value2) {
            addCriterion("proname between", value1, value2, "proname");
            return (Criteria) this;
        }

        public Criteria andPronameNotBetween(String value1, String value2) {
            addCriterion("proname not between", value1, value2, "proname");
            return (Criteria) this;
        }

        public Criteria andPropriceIsNull() {
            addCriterion("proprice is null");
            return (Criteria) this;
        }

        public Criteria andPropriceIsNotNull() {
            addCriterion("proprice is not null");
            return (Criteria) this;
        }

        public Criteria andPropriceEqualTo(String value) {
            addCriterion("proprice =", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceNotEqualTo(String value) {
            addCriterion("proprice <>", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceGreaterThan(String value) {
            addCriterion("proprice >", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceGreaterThanOrEqualTo(String value) {
            addCriterion("proprice >=", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceLessThan(String value) {
            addCriterion("proprice <", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceLessThanOrEqualTo(String value) {
            addCriterion("proprice <=", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceLike(String value) {
            addCriterion("proprice like", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceNotLike(String value) {
            addCriterion("proprice not like", value, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceIn(List<String> values) {
            addCriterion("proprice in", values, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceNotIn(List<String> values) {
            addCriterion("proprice not in", values, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceBetween(String value1, String value2) {
            addCriterion("proprice between", value1, value2, "proprice");
            return (Criteria) this;
        }

        public Criteria andPropriceNotBetween(String value1, String value2) {
            addCriterion("proprice not between", value1, value2, "proprice");
            return (Criteria) this;
        }

        public Criteria andProaddressIsNull() {
            addCriterion("proaddress is null");
            return (Criteria) this;
        }

        public Criteria andProaddressIsNotNull() {
            addCriterion("proaddress is not null");
            return (Criteria) this;
        }

        public Criteria andProaddressEqualTo(String value) {
            addCriterion("proaddress =", value, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressNotEqualTo(String value) {
            addCriterion("proaddress <>", value, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressGreaterThan(String value) {
            addCriterion("proaddress >", value, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressGreaterThanOrEqualTo(String value) {
            addCriterion("proaddress >=", value, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressLessThan(String value) {
            addCriterion("proaddress <", value, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressLessThanOrEqualTo(String value) {
            addCriterion("proaddress <=", value, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressLike(String value) {
            addCriterion("proaddress like", value, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressNotLike(String value) {
            addCriterion("proaddress not like", value, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressIn(List<String> values) {
            addCriterion("proaddress in", values, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressNotIn(List<String> values) {
            addCriterion("proaddress not in", values, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressBetween(String value1, String value2) {
            addCriterion("proaddress between", value1, value2, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProaddressNotBetween(String value1, String value2) {
            addCriterion("proaddress not between", value1, value2, "proaddress");
            return (Criteria) this;
        }

        public Criteria andProimageIsNull() {
            addCriterion("proimage is null");
            return (Criteria) this;
        }

        public Criteria andProimageIsNotNull() {
            addCriterion("proimage is not null");
            return (Criteria) this;
        }

        public Criteria andProimageEqualTo(String value) {
            addCriterion("proimage =", value, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageNotEqualTo(String value) {
            addCriterion("proimage <>", value, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageGreaterThan(String value) {
            addCriterion("proimage >", value, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageGreaterThanOrEqualTo(String value) {
            addCriterion("proimage >=", value, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageLessThan(String value) {
            addCriterion("proimage <", value, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageLessThanOrEqualTo(String value) {
            addCriterion("proimage <=", value, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageLike(String value) {
            addCriterion("proimage like", value, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageNotLike(String value) {
            addCriterion("proimage not like", value, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageIn(List<String> values) {
            addCriterion("proimage in", values, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageNotIn(List<String> values) {
            addCriterion("proimage not in", values, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageBetween(String value1, String value2) {
            addCriterion("proimage between", value1, value2, "proimage");
            return (Criteria) this;
        }

        public Criteria andProimageNotBetween(String value1, String value2) {
            addCriterion("proimage not between", value1, value2, "proimage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 29 10:59:12 CST 2022
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbggenerated Tue Nov 29 10:59:12 CST 2022
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}